FROM nginx:alpine

COPY ./entrypoint-nginx.sh /

RUN set -ex && \
	apk add --no-cache bash && \
	chmod +x /entrypoint-nginx.sh

COPY ./vhost.conf.sample /etc/nginx/conf.d/vhost.conf.sample

CMD ["/entrypoint-nginx.sh"]
